### ISSUE TITLE
[Bug]: Not working after basic install

### ISSUE THREAD

**Issue by Rizhiy** [chrisgrieser/nvim-scissors#1]
### Bug Description

Installed using Lazy, when trying to run any function getting the following error:
```
 E5108: Error executing lua: ...azy/nvim-scissors/lua/scissors/read-write-operations.lua:22: package.json could not be read
 stack traceback:
 ▸   [C]: in function 'assert'
 ▸   ...azy/nvim-scissors/lua/scissors/read-write-operations.lua:22: in function 'readAndParseJson'
 ▸   ...e/nvim/lazy/nvim-scissors/lua/scissors/vscode-format.lua:21: in function 'getSnippetFilesForFt'
 ▸   ...ocal/share/nvim/lazy/nvim-scissors/lua/scissors/init.lua:74: in function 'addNewSnippet'
 ▸   /home/rizhiy/.config/nvim/lua/plugins/cmp.lua:25: in function </home/rizhiy/.config/nvim/lua/plugins/cmp.lua:25>
```

### To Reproduce

Install it using lazy and try to execute using Lua

### neovim version

```Text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
As the error message says: it looks like you are missing a package.json specifying your snippet Information in your snippet directory, which is required for this plugin to work.

**Comment by Rizhiy** [comment]
I don't know how snippets work underneath, can't you create a standard one by default?

**Comment by chrisgrieser** [comment]
Hmm yeah, in that case it's about bootstrapping a vs code snippet dir, which would go into a similar direction as #2

**Comment by FormalSnake** [comment]
where can I get said package.json?

**Comment by FormalSnake** [comment]
rn I am using the one from your dot files

**Comment by chrisgrieser** [comment]
@FormalSnake I added the automatic bootstrapping of the `package.json` if none exists in your snippet file in the last few commits. 

I'll also add a section explaining the requirements for the package.json to the readme momentarily.

**Comment by FormalSnake** [comment]
nice, thank you.

**Comment by chrisgrieser** [comment]
I added an FAQ showing the requirements for the VSCode-style snippet format:
https://github.com/chrisgrieser/nvim-scissors#cookbook--faq
