### ISSUE TITLE
Is there a plan to support coq's snip

### ISSUE THREAD

**Issue by ilan-schemoul** [chrisgrieser/nvim-scissors#12]
### Feature Requested

Coq uses its own format for snippet (.snip) and need :COQsnips to compile after modify snippets

Is it part of the scope of the project to support other formats or is out of scope ?

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
I personally do not use `coq` and therefore have no plans of my own to add support for them, but I am open for PRs adding support for it. The things specific to the vs-code format are already isolated into their own module.

**Comment by ilan-schemoul** [comment]
Ok.
Personally I will not do this because looking at the code it's a bit too much work relative to how much I use snippets. I could not find an equivalent of your plugin for coq either, if someone knows lmk.

**Comment by chrisgrieser** [comment]
Yeah, it would have to be a bigger PR indeed. 

To my knowledge, there is no other plugin that allows you to edit snippets the way scissors does.

**Comment by ilan-schemoul** [comment]
Well,
You can close this. It makes more sense for this plugin to only focus on one standard instead of each non standard format. Anyway cmp UI is much better, snippet support is much better, it works with Noice etc. (I switched to cmp I don't see much future to coq)
