### ISSUE TITLE
Is there a way to change the binding to jump to next token?

### ISSUE THREAD

**Issue by ktandun** [chrisgrieser/nvim-scissors#13]
### Feature Requested

Currently it uses Tab but is it possible to configure it to something else?
I am using this plugin without LuaSnip

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
No, jumping to the next token is done by your snippet engine, not by nvim-scissors. In fact, this plugin does not create any keybinding for `tab`.

If you do not Luasnip, it depends on whatever snippet engine plugin you use; I'd check their respective documentation.

**Comment by ktandun** [comment]
That makes sense, thanks!
