### ISSUE TITLE
[Bug]: error afer key enter in add new snippet

### ISSUE THREAD

**Issue by mohamad-supangat** [chrisgrieser/nvim-scissors#18]
### Bug Description

after key enter to save new snippet i got a error, but snippet file updated in snippet folder

### Relevant Screenshot

![Screenshot 2024-06-12 092137](https://github.com/chrisgrieser/nvim-scissors/assets/48933993/58a0b0bf-5b84-4b3e-94ba-08cfc2f13573)

### To Reproduce

1. Select some text in virtual mode
2. using keymap `<leader>sa` to create snippet
3. insert prefix or title
4. key `esc` back to normal mode and key `enter` to save

### neovim version

```Text
NVIM v0.10.0
Build type: Release
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read [the plugin's FAQ](https://github.com/chrisgrieser/nvim-scissors#cookbook--faq).

**Comment by chrisgrieser** [comment]
thanks, fixed.

btw, that error did only occur when you did not use LuaSnip or nvim-snippets. What snippet engine are you using? Cause I am actually not aware of any other

**Comment by mohamad-supangat** [comment]
> thanks, fixed.
> 
> btw, that error did only occur when you did not use LuaSnip or nvim-snippets. What snippet engine are you using? Cause I am actually not aware of any other

Tanks for fix this, i use https://github.com/hrsh7th/vim-vsnip


btw who is better vim-vsnip or luasnip for vscode snippet support ?

**Comment by chrisgrieser** [comment]
Ah, I didn't know about vsnip, interesting.

Generally, luasnip or nvim-snippets are preferrable, since both have reload functiosn, meaning you do not have to restart vim after editing/adding a snippet with scissors.

luasnip is the more complicated, but also more customizable plugin, while nvim-snippets is the simpler plugin. Lazyvim (the nvim distro) uses nvim-snippets.

**Comment by chrisgrieser** [comment]
btw, if you wanna keep on using vsnip, I just added support for hot-reloading with it in https://github.com/chrisgrieser/nvim-scissors/commit/dc039a7cc3eca12eaea617b1a8cf6d12a2ae14fb

**Comment by mohamad-supangat** [comment]
Thanks fot this awesome plugin @chrisgrieser
