### ISSUE TITLE
Feature Request: Bootstrap vscode snippet folder

### ISSUE THREAD

**Issue by Rizhiy** [chrisgrieser/nvim-scissors#2]
### Feature Requested

After install, if the default snippet directory doesn't exist, the following error is raised:
```
Snippet directory does not exist: /home/rizhiy/.config/nvim/snippets
```
Would be great if the default directory is created automatically.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Unfortunately, this would not help much, since it is not only a snippet directory, but also a package.json and at least one snippet file for vs code snippets to work. And that, in turn, is not something this plugin can easily automate for the user. 

Considering your other issues, I'd suggest reading up on the docs how the vs code snippet format works.

**Comment by Rizhiy** [comment]
One directory and two files are not easy?

**Comment by chrisgrieser** [comment]
Not easy in the sense that strictly speaking it requires user input. Though I suppose bootstrapping with some default values could probably work

**Comment by chrisgrieser** [comment]
With all the necessary validation and covering all cases, this "easy" implementation took a total of ~120 lines.

Anyway, the last update now adds bootstrapping capabilities if the snippet directory, the `package.json`, or a snippet file is missing.

**Comment by Rizhiy** [comment]
Adding snippets works fine, thank you.
If I try to edit snippets without directory/package.json it still errors out, would be great to also create those files on edit snippets call.

**Comment by Rizhiy** [comment]
Also, might be a good idea to ask the user if they want to create the files if they don't exists. In case someone mistyped the snippetsDir by accident.

**Comment by chrisgrieser** [comment]
Adding a snippet file when you are trying to edit existing snippets feels a bit unintuitive for me, tbh.

But validating that a package.json exists before you try to edit snippet files is indeed something that is missing and that I'll add in a moment.
