### ISSUE TITLE
Feature Request: Allow custom jsonFormatter

### ISSUE THREAD

**Issue by MasouShizuka** [chrisgrieser/nvim-scissors#20]
### Checklist

- [X] The feature would be useful to more users than just me.
- [X] The suggestion is related to creating or editing snippets. (Expanding and using snippet is the responsibility of the snippet engine plugin, such as Luasnip or nvim-snippets.)

### Feature Requested

When `jsonFormatter` is passed an array, it can be used as a command to format jsonstr.

For example, if want to set `jq`'s `indent` to 4:
```lua
jsonFormatter = { "jq", "--sort-keys", "--monochrome-output", "--indent", 4 }
```

**Comment by chrisgrieser** [comment]
good idea, added.
