### ISSUE TITLE
Feature Request: Allows defining a title different from the prefix

### ISSUE THREAD

**Issue by MasouShizuka** [chrisgrieser/nvim-scissors#21]
### Checklist

- [X] The feature would be useful to more users than just me.
- [X] The suggestion is related to creating or editing snippets. (Expanding and using snippet is the responsibility of the snippet engine plugin, such as Luasnip or nvim-snippets.)

### Feature Requested

Currently defined snippets have the same title and prefix, but they can contain more information, for example:
```json
    "Module template": {
        "body": [
            "local M = {}",
            "${TM_SELECTED_TEXT}$0",
            "return M"
        ],
        "description": "This is a module template",
        "prefix": "M"
    },
```
This will look like:
![image](https://github.com/user-attachments/assets/b1e95f20-4ff6-4440-9ec2-d9e743507858)

So it would be great if could allow custom title and description.

**Comment by chrisgrieser** [comment]
That would require rewriting the plugin's UI to support somehow writing more than the snippet body and snippet prefix. Not impossible, but would take a certain amount of work, and make the plugin more complicated to use, while ease-of-use is one of its goals.

In my view, the benefit of being able to define a title different from the prefix is not big enough to warrant implementing this. For the very few cases where this might be useful, you can use the `openInFile` keymap to edit the title directly.

**Comment by MasouShizuka** [comment]
After editing and saving an existing snippet, the title will be overwritten with the prefix.

For example, after saving the above snippet, it will become:
```json
    "M": {
        "body": [
            "local M = {}",
            "${TM_SELECTED_TEXT}$0",
            "return M"
        ],
        "description": "This is a module template",
        "prefix": "M"
    },
```
In addition, it is also found that the part of `luasnip` will disappear:
```json
    "Insert heading level 1": {
        "prefix": [
            ".1",
            "。1"
        ],
        "body": "# ${TM_SELECTED_TEXT}",
        "luasnip": {
            "autotrigger": true
        },
        "description": "Insert heading level 1"
    },
```
become:
```json
    ".1 + 。1": {
        "body": "# ${TM_SELECTED_TEXT}",
        "description": "Insert heading level 1",
        "prefix": [
            ".1",
            "。1"
        ]
    },
```

Is it possible to prevent other parts from being overwritten?

**Comment by chrisgrieser** [comment]
good point. Should be fixed.

**Comment by MasouShizuka** [comment]
After this fix, some keys that were not originally there appear after the snippet is saved, such as the above snippet:
```json
    "Module template": {
        "body": [
            "local M = {}",
            "${TM_SELECTED_TEXT}$0",
            "return M"
        ],
        "description": "This is a module template",
        "filetype": "lua",
        "fullPath": "C:/Users/MasouShizuka/scoop/persist/vscode/data/user-data/User/snippets/lua.json",
        "originalKey": "Module template",
        "prefix": "M"
    },
```

**Comment by chrisgrieser** [comment]
fixed
