### ISSUE TITLE
Feature Request: document interaction with 'mini.snippets'

### ISSUE THREAD

**Issue by echasnovski** [chrisgrieser/nvim-scissors#24]
### Checklist

- [X] I have read the plugin's README, including the FAQ.
- [X] The suggestion is related to creating or editing snippets. (Expanding and using snippet is the responsibility of the snippet engine plugin, such as `Luasnip` or `nvim-snippets`.)
- [X] The feature would be useful to more users than just me.

### Feature Requested

Document interaction with ['mini.snippets'](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-snippets.md).

### Problem solved

Problem of no documentation about 'mini.snippets'.

### Alternatives considered

Making PR directly, but I decided to clarify some details first.

There are several details that make choice of documentation text not as clear:
- 'mini.snippets' out of the box doesn't set up any snippet loading leaving the choice to the user. There is a [suggested basic example](https://github.com/echasnovski/mini.nvim/blob/2011aff270bcd3e1f3ad088253ace2d574967bed/doc/mini-snippets.txt#L372-L383), though.
- There are [built-in loader generators](https://github.com/echasnovski/mini.nvim/blob/2011aff270bcd3e1f3ad088253ace2d574967bed/doc/mini-snippets.txt#L702):
    - Both [`from_lang()`](https://github.com/echasnovski/mini.nvim/blob/2011aff270bcd3e1f3ad088253ace2d574967bed/doc/mini-snippets.txt#L720) and [`from_runtime()`](https://github.com/echasnovski/mini.nvim/blob/2011aff270bcd3e1f3ad088253ace2d574967bed/doc/mini-snippets.txt#L772) will read files from all 'snippets/' directories. The `from_runtime()` output will match some input glob pattern (`'**/lua.json'` is equivalent to 'snippets/**/lua.json' runtimepath glob) and `from_lang()` will automatically compute those patterns based on local language.
    - There is also [`from_file()`](https://github.com/echasnovski/mini.nvim/blob/2011aff270bcd3e1f3ad088253ace2d574967bed/doc/mini-snippets.txt#L804) loader generator and a low-level [`read_file()`](https://github.com/echasnovski/mini.nvim/blob/2011aff270bcd3e1f3ad088253ace2d574967bed/doc/mini-snippets.txt#L820).

All of this flexibility makes it not easy to choose one documented approach.

------

I think the best approach would be to have something like this:
- Recommend setting the following directory for 'nvim-scissors':
    ```lua
    require('scissors').setup({
      snippetDir = vim.fn.stdpath('config') .. '/snippets',
    })
    ```
- Suggest text of [basic setup](https://github.com/echasnovski/mini.nvim/blob/2011aff270bcd3e1f3ad088253ace2d574967bed/doc/mini-snippets.txt#L372-L383) together with some notes like "When adding custom file loaders according to 'mini.snippets' documentation, make sure that files are inside 'nvim-scissors' snippet directory".

Does this sound good?

**Comment by echasnovski** [comment]
By the way, very cool plugin indeed. Just tried it for the first time, feels quite intuitive. The only thing that got me confused was Telesclope-like UI which made me stumble for about a minute about how to navigate to the bottom window. Only noticing line numbers (because I have 'number' enabled) made me realize that this is a single window. Without 'number' I would have been completely lost.

**Comment by chrisgrieser** [comment]
Sure, such a PR sounds good. If the setup for mini-snippets is more elaborate than with other snippet plugins described in the readme, we might also consider to simply link to a section of mini.snippet's Readme. That way you can make changes there instead of having to make a PR again when you change something for mini.snippets?

Taking a quick look through mini.snippet's docs it also looks like you can use it with snippet files in the VS code format, but also with snippets saved in lua tables, or in json files but without a package.json? Think one important thing to point out for users is that scissors requires a package.json as well as json files. So users with snippets just in lua format would have to convert them.

**Comment by chrisgrieser** [comment]
Also, while we are at it, does mini.snippets expose a function for reloading snippets? If so, the PR could also include mini.snippets hot-reloading support by adding a few lines in `hot-reload.lua`. That way you can edit snippets on the fly without restarting nvim.

**Comment by chrisgrieser** [comment]
> The only thing that got me confused was Telesclope-like UI which made me stumble for about a minute about how to navigate to the bottom window.

Good point. I made it one window to make adding/removing additional prefixes more intuitive. Maybe changing the styling of the border could make it appear less like two windows 🤔

**Comment by echasnovski** [comment]
> Think one important thing to point out for users is that scissors requires a package.json as well as json files. So users with snippets just in lua format would have to convert them.

I've just tried creating a snippet and later editing it. Seems like it worked as expected (without hot-reloading, though, which is rather  straightforward to add).

> Also, while we are at it, does mini.snippets expose a function for reloading snippets? If so, the PR could also include mini.snippets hot-reloading support by adding a few lines in `hot-reload.lua`. That way you can edit snippets on the fly without restarting nvim.

'mini.snippets' always "prepares" (resolves/normalizes) all snippets before each expand. The performance/speed is good because loaders [cache their outputs](https://github.com/echasnovski/mini.nvim/blob/2011aff270bcd3e1f3ad088253ace2d574967bed/doc/mini-snippets.txt#L710-L714). The best "hot-reload" available is (and probably will be) simply clearing whole cache as described in the help: `MiniSnippets.setup(MiniSnippets.config)`. Just tested and it seems to work with 'nvim-scissors' also.

> Good point. I made it one window to make adding/removing additional prefixes more intuitive. Maybe changing the styling of the border could make it appear less like two windows 🤔

I think having some blank space (in the middle or in the right part) of the horizontal "window separator" would have helped.

**Comment by chrisgrieser** [comment]
> >Think one important thing to point out for users is that scissors requires a package.json as well as json files. So users with snippets just in lua format would have to convert them.
>
> I've just tried creating a snippet and later editing it. Seems like it worked as expected

Yes, but if you want to edit existing snippets saved in lua files, for instance, it won't work. And I am afraid that if we do not explicitly mention that, at some point people are gonna open bug reports at either scissors or mini.snippets

> The best "hot-reload" available is (and probably will be) simply clearing whole cache as described in the help: MiniSnippets.setup(MiniSnippets.config). Just tested and it seems to work with 'nvim-scissors' also.

I think for most of the other snippet plugins, their reload function is pretty much just cache clearing, tbh. So that's totally fine!

> I think having some blank space (in the middle or in the right part) of the horizontal "window separator" would have helped.

I played around a bit and settled for a dashed line which should evoke "permeability" to the user
![Pasted image 2024-12-24 at 19 44 49@2x](https://github.com/user-attachments/assets/e0f06839-aaf7-4eef-b181-1531c27f8820)

**Comment by echasnovski** [comment]
> I played around a bit and settled for a dashed line which I should evoke "permeability" to the user

Yeah, that looks better. I *think* I'd still struggle at first about how to actually "change focus" from editing snippet prefix to editing snippet body. The fact that it is plain `<Down>` is something that needs to be learned.

Also, a bit of a stretch, but I also struggled for a second (several times) with the fact that mappings from the window footer are for Normal mode. There are couple of `<C-...>` ones which might as well be in Insert mode. But not sure what else can be done here.

**Comment by echasnovski** [comment]
> Yes, but if you want to edit existing snippets saved in lua files, for instance, it won't work. And I am afraid that if we do not explicitly mention that, at some point people are gonna open bug reports at either scissors or mini.snippets

Yeah, for sure. Added that explicitly in #25. I was just confused why 'package.json' would be required.

**Comment by chrisgrieser** [comment]
> I was just confused why 'package.json' would be required.

nvim-scissors actually uses the `package.json` to determine the filetype(s) of a snippet. If you add a snippet, and it's missing, it will be auto-created for your though. So the remaining edge case would only be a user using mini.snippets without json files but without a package.json, and then trying to use nvim-scissors.

**Comment by chrisgrieser** [comment]
yeah, properly teaching users about keymaps is really tricky. I made some improvements to the keymap hints and added a `showHelp` keymap, which should hopefully make the onboarding easier?

![Pasted image 2024-12-24 at 21 51 31@2x](https://github.com/user-attachments/assets/e7d5af55-82e6-4287-bec4-465b5116a696)

**Comment by echasnovski** [comment]
> yeah, properly teaching users about keymaps is really tricky. I made some improvements to the keymap hints and added a `showHelp` keymap, which should hopefully make the onboarding easier?

Yeah, I think it is. More hints more better :)
Not sure about the usage of `vim.notify`, as with notification plugin the window will be hidden relatively quickly for the amount of text. But shouldn't be a big deal.

**Comment by chrisgrieser** [comment]
> Not sure about the usage of vim.notify, as with notification plugin the window will be hidden relatively quickly for the amount of text.

that's why I explicitly set a higher timeout for this one notification ;)

(Thought about just keeping the notification indefinitely, but not every user has a keymap set for dismissing notifications, so I just settled for a loner timeout.)

**Comment by echasnovski** [comment]
> > Not sure about the usage of vim.notify, as with notification plugin the window will be hidden relatively quickly for the amount of text.
> 
> that's why I explicitly set a higher timeout for this one notification ;)
> 
> (Thought about just keeping the notification indefinitely, but not every user has a keymap set for dismissing notifications, so I just settled for a loner timeout.)

Ah, I see the source of my confusion. The issue here is that `vim.notify` doesn't document any options that its implementations can use (unlike `vim.ui.select`, for example). So setting `title`, `icon`, and `timeout` might have no effect for the user. This is the case for 'mini.notify' which displays info notifications for 5 seconds, which felt just a shy too few for a comfortable reading.
