### ISSUE TITLE
Feature Request: Being able to edit snippets from other providers

### ISSUE THREAD

**Issue by Rizhiy** [chrisgrieser/nvim-scissors#3]
### Feature Requested

Not sure if it is possible, but being able to edit snippets from other providers (e.g. friendly-snippets) would be useful.
Perhaps add a new snippet with the same name, but higher priority.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
You already can edit snippets from friendly snippets. Just set the location where friendly snippets is installed as your `snippetDir`

**Comment by Rizhiy** [comment]
To save people time, here is the setting when using lazy.nvim:
```lua
{
    "chrisgrieser/nvim-scissors",
    opts = { snippetDir = vim.fn.stdpath("data") .. "/lazy/friendly-snippets" },
},
```

**Comment by chrisgrieser** [comment]
Be aware that editing them specify also saves them in the friendly snippets plugin dir, meaning changes you make will be lost as soon as friendly snippets is updated. 

Copying some snippet files from friendly snippets into your own snippet collection might make more sense
