### ISSUE TITLE
[Bug]: Cannot add multiline snippets

### ISSUE THREAD

**Issue by Sombrer0Dev** [chrisgrieser/nvim-scissors#4]
### Bug Description

If i try to add a new line before code snippet in preselected snippet or add a new line in an empty snippet it will start to register as a prefix

### Relevant Screenshot

# New snippet
(no new line)  
![image](https://github.com/chrisgrieser/nvim-scissors/assets/90571229/894bd499-6820-4206-b80e-5a47fd9115fd)

(new line)
![image](https://github.com/chrisgrieser/nvim-scissors/assets/90571229/69f80aa4-b58d-4f66-84a5-02829452def3)

# Preselected snippet  
(no new line)
![image](https://github.com/chrisgrieser/nvim-scissors/assets/90571229/86fa4bb3-df39-4a2b-a0de-303a121671e7)

(new line before selected text)
![image](https://github.com/chrisgrieser/nvim-scissors/assets/90571229/0f9eeb77-b6fd-4863-91e2-8fd81b608009)

### To Reproduce

# New snippet
1. require("scissors").addNewSnippet()
2. write a prefix
3. write something on a new line
4. carriage return
# Preselected snippet
1. require("scissors").addNewSnippet() in a visual mode
2. write a prefix
3. new line before selected text
4. 

### neovim version

```Text
NVIM v0.10.0-dev-1988+g1ef60ea651
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read [the plugin's FAQ](https://github.com/chrisgrieser/nvim-scissors#cookbook--faq).

**Comment by chrisgrieser** [comment]
I am not entirely sure whether this is the issue you have, but due to the way this plugin treats positions the divider line (between prefix and body), pressing `o` on a prefix line creates another prefix line. 

To add a new line something to the body, you'd have to press `j`, and then `i`.

**Comment by chrisgrieser** [comment]
Okay, I tweaked the behavior a bit, `o` on the prefix line now simply adds a line to be body. `O` on a prefix line still creates a new prefix line. Think that should be more intuitive.

**Comment by zolrath** [comment]
Edit: Hey you fixed this as I was writing the comment, nice.

I think the issue is if you:

- set a prefix
- then hit esc, move down to the snippet line
- start a snippet and then hit enter

the first line of the snippet moves up to the prefix.

Before hitting enter:
![image](https://github.com/chrisgrieser/nvim-scissors/assets/454563/f32c826b-baac-4fcf-aefe-17f14c7e985e)
after pressing enter:
![image](https://github.com/chrisgrieser/nvim-scissors/assets/454563/bba5983d-a6bf-4198-9325-914a71265866)

**Comment by chrisgrieser** [comment]
@zolrath that behavior should be fixed with the latest commit I made a few seconds before your comment :P
