### ISSUE TITLE
Feature Request: Search for snippet via snippet body

### ISSUE THREAD

**Issue by zolrath** [chrisgrieser/nvim-scissors#7]
### Feature Requested

Hi!
Sometimes I know I have a snippet that adds a specific line of text but I can't remember what it uses as a prefix.
It would be great to be able to search through the snippet edit popup using the contents of the snippets instead of just the prefix.

### Relevant Screenshot

Given that I have snippets that say `:noreply`
![image](https://github.com/chrisgrieser/nvim-scissors/assets/454563/03080a59-d9d0-45d9-b5b0-8efa814eb138)

Imagine if instead of no results, all snippets containing the text `noreply` would appear in the list.
![image](https://github.com/chrisgrieser/nvim-scissors/assets/454563/2af63cf0-45c1-4830-8755-0fd9e0506fd0)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Good idea.  Since it might be a bit unintuitive for new users, I disabled the feature by default. 

Set `telescope.alsoSearchSnippetBody = true` to enable this.
