### ISSUE TITLE
Feature Request: Multiple keymaps for same action in edit window

### ISSUE THREAD

**Issue by garymh** [chrisgrieser/nvim-scissors#9]
### Feature Requested

Hi there! Love the plugin! I just have a small request- I have a keybinding `vim.keymap.set("<leader>w", vim.cmd.w)` that I use to save usually, and that ends up throwing an error in the snippet edit window since I'm not calling `:w` directly. Is there a way to add additional aliases?

I'm not a plugin author by any means, but maybe there could be a special buffer type here https://github.com/chrisgrieser/nvim-scissors/blob/f7a24fbbb10c1c87f1907e57de5f384cc01baf24/lua/scissors/edit-popup.lua#L161 instead of `nofile`? Does that work with `ftplugin` files? (or is that just filetypes)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
That does not work, because the snippet window isn't a real file. 

Why you not just set the `saveChanges` keymap of this plugin to `<leader>w`?

**Comment by garymh** [comment]
> That does not work, because the snippet window isn't a real file.

Ah, darn

> Why you not just set the saveChanges keymap of this plugin to <leader>w?

Mostly because I also do `:w` as well. Just kind of depends how fast I'm typing at the moment 🙃

**Comment by chrisgrieser** [comment]
So both, `<leader>w` as well as `:w`, are covered. What exactly is your issue then?

**Comment by garymh** [comment]
Sorry - should have clarified, I was trying to teach myself to use `<CR>` too. But until that muscle memory started working, I figured it might be nice to have multiple options. (I was thinking of a few ways to access `jumpBetweenBodyAndPrefix` too)

**Comment by chrisgrieser** [comment]
Ah, so you want to be able to set multiple keymaps?

**Comment by garymh** [comment]
Yes, that's a better way of putting 😄

**Comment by chrisgrieser** [comment]
If you set your keymap like this:
```lua
vim.keymap.set("n", "<leader>w", ":w<CR>")
```
Then `<leader>w` will work to save the snippet, regardless of what you set the `saveChanges` key to. (It needs to be via `:` for nvim-scissors overwrite to take effect). 

This means that you can use `<CR>` for `saveChanges` as well, giving you a total of 3 options for how you can save changes. Adding extra options for multiple keymaps beyond that feels somewhat unnecessary for me. 

If there are other people also requesting the multiple keymaps, I'll reconsider, though.
